---
- name: install nginx
  homebrew:
    name: nginx
    state: present
  notify: restart nginx
  tags: setup

- name: create folders for vhosts
  file:
    path: "{{ webdev_projectspath }}"
    state: directory
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  tags: setup

- name: configure nginx
  template:
    dest: "{{ webdev_homebrew_rootpath }}etc/nginx/nginx.conf"
    src: 'nginx.conf.j2'
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  notify: restart nginx
  tags: setup

- name: create vhost configuration folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  with_items:
    - "{{ webdev_homebrew_rootpath }}etc/nginx/sites-available"
    - "{{ webdev_homebrew_rootpath }}etc/nginx/sites-enabled"
  notify: restart nginx
  tags: setup

- name: set permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webdev_user }}"
    group: "{{ webdev_group }}"
    mode: 0775
    recurse: yes
  with_items:
    - /usr/local/etc/nginx/
  tags: setup

- name: create symlink for LaunchDaemon
  file:
    path: "/Library/LaunchDaemons/homebrew.mxcl.nginx.plist"
    state: link
    src: "/usr/local/opt/nginx/homebrew.mxcl.nginx.plist"
  sudo: true
  notify: restart nginx
  tags: setup

- name: create instance
  include: create_instance.yml
  when: name is defined