---
- name: install java
  homebrew_cask:
    name: java
    state: present
  tags: setup

- name: "add homebrew tap 'versions'"
  homebrew_tap:
    tap: "homebrew/versions"
    state: present
  tags: setup

- name: create configuration folder
  file:
    path: /usr/local/etc/elasticsearch
    state: directory
  tags: setup

- name: install elasticsearch
  homebrew:
    name: elasticsearch17
    state: present
  notify: restart elasticsearch
  tags: setup

- name: configure elasticsearch for Neos
  template:
    dest: /usr/local/Cellar/elasticsearch17/1.7.4/config/elasticsearch.yml
    src: elasticsearch.yml.j2
  notify: restart elasticsearch
  tags: setup

- name: create folder for LaunchAgents
  file:
    path: "{{ webdev_home }}Library/LaunchAgents"
    state: directory
    owner: "{{ webdev_user }}"
  tags: setup

- name: create symlink for LaunchAgent
  file:
    path: "{{ webdev_home }}Library/LaunchAgents/homebrew.mxcl.elasticsearch17.plist"
    state: link
    src: "{{ webdev_homebrew_rootpath }}opt/elasticsearch17/homebrew.mxcl.elasticsearch17.plist"
  notify: restart elasticsearch
  tags: setup
